export { h } from "./h"
export { createTextVNode } from "./vnode"
export { renderSlots } from "./helpers/renderSlots"
export { provide, inject } from "./provide_inject"
export { createRenderer } from "./render"
export { getCurrentInstance } from "./component"